import Header from "./components/Header/Header";
import TnastackProvider from "./components/providers/TanstackProvider";
import "./index.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <TnastackProvider>
          <div className="wrapper">
            <Header />
            {children}
            <footer>
              <div className="container">Footer</div>
            </footer>
          </div>
        </TnastackProvider>
      </body>
    </html>
  );
}
