import TnastackProvider from "./components/providers/TanstackProvider";
import "./index.scss";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <TnastackProvider>
          <div className="wrapper">
            <header>
              <div className="container">
                <div>
                  <Link href="/">Logo</Link>
                </div>
                <ul>
                  <li>
                    <Link href="/shop">Shop</Link>
                  </li>
                </ul>
              </div>
            </header>
            {children}
            <footer>
              <div className="container">Footer</div>
            </footer>
          </div>
        </TnastackProvider>
      </body>
    </html>
  );
}
